CREATE DATABASE ICP_W5D3;
USE ICP_W5D3;

-- Creo tabella Prodotto
CREATE TABLE Prodotto
	(ID_PRODOTTO INT AUTO_INCREMENT
    , PREZZO_UNIT DECIMAL(10,4)
    , COD_PROD VARCHAR(50)
    , CONSTRAINT PK_Prodotto PRIMARY KEY (ID_PRODOTTO)
    );
-- Creo tabella Ordine
CREATE TABLE Ordine
	(ID_ORDINE INT
    , DATA_ORDINE DATE
    , PREZZO_ORDINE DECIMAL(10,4)
    , ID_PRODOTTO INT 
    , CONSTRAINT PK_Ordine PRIMARY KEY (ID_ORDINE)
    , CONSTRAINT FK_Ordine FOREIGN KEY (ID_PRODOTTO) REFERENCES Prodotto (ID_PRODOTTO)
    ); 
    
-- Creo tabella Fornitore
CREATE TABLE Fornitore
	(ID_FORNITORE VARCHAR(50)
    , NOME_FORNITORE VARCHAR(50)
    , PIVA INT
    , TELEFONO INT 
    , ID_ORDINE INT 
    , CONSTRAINT PK_Fornitore PRIMARY KEY (ID_FORNITORE)
    , CONSTRAINT FK_Fornitore FOREIGN KEY (ID_ORDINE) REFERENCES Ordine (ID_ORDINE)
    ); 

-- Creo tabella Stabilimento
CREATE TABLE Stabilimento
	(ID_STAB INT 
    , NOME_STAB VARCHAR(50)
    , INDIRIZZO_STAB VARCHAR(50)
    , ID_PRODOTTO INT 
    , CONSTRAINT PK_Stabilimento PRIMARY KEY (ID_STAB)
    , CONSTRAINT FK_Stabilimento FOREIGN KEY (ID_PRODOTTO) REFERENCES Prodotto (ID_PRODOTTO)
    );

-- Creo tabella Cava
CREATE TABLE Cava
	(ID_CAVA INT 
    , NOME_CAVA VARCHAR(50)
    , CAT_CAVA VARCHAR(50)
    , INDIRIZZO_CAVA VARCHAR(50)
    , CONSTRAINT PK_Cava PRIMARY KEY (ID_CAVA)
    );

-- Creo tabella Argilla
CREATE TABLE Argilla
	(ID_ARGILLA INT 
    , ID_CAVA INT 
    , ID_STAB INT 
    , CONSTRAINT PK_Argilla PRIMARY KEY (ID_ARGILLA)
    , CONSTRAINT FK_Cava FOREIGN KEY (ID_CAVA) REFERENCES Cava (ID_CAVA)
    , CONSTRAINT FK_Stab FOREIGN KEY (ID_STAB) REFERENCES Stabilimento (ID_STAB)
    ); 

-- Popolamento tabelle
INSERT INTO
	 Prodotto (ID_PRODOTTO, PREZZO_UNIT, COD_PROD)
VALUES 
	(1, 20.5, 'A1B1');

INSERT INTO 
	Ordine (ID_ORDINE, DATA_ORDINE, PREZZO_ORDINE, ID_PRODOTTO)
VALUES
	(001, '2020-03-24', 800.67, 1);

INSERT INTO 
	 Fornitore (ID_FORNITORE, NOME_FORNITORE, PIVA, TELEFONO, ID_ORDINE)
VALUES 
	(12, 'DUBLINO', 1234, 0456780985, 001);
	
INSERT INTO
	Stabilimento (ID_STAB, NOME_STAB, INDIRIZZO_STAB, ID_PRODOTTO)
VALUES 
	(111, 'ILCA','VIA ZERO 2', 1);
		 
INSERT INTO
	Cava (ID_CAVA, NOME_CAVA, CAT_CAVA, INDIRIZZO_CAVA)
VALUES
	(222, 'ROSSA', 'FERROSA', 'VIA FERMI 3');

INSERT INTO 
	 Argilla (ID_ARGILLA, ID_CAVA, ID_STAB)
VALUES
	(333, 222, 111);
    	